### ISSUE TITLE
please include bash scripts

### ISSUE THREAD

**Issue by mikegilchrist** [acope3/Intragenomic_variation_mutation_bias#2]
The README.md file has some bash code, but "$INPUT" and "$OUTPUT" are not defined.  Could you please add the scripts you used to run 'ca.R' and 'rocAnalysis.R'?

**Comment by acope3** [comment]
Hey @mikegilchrist, command-line arguments for the R scripts are defined in R scripts using the `argparse` library. You can get these via `Rscript --vanilla Scripts/rocAnalysis.R --help`.

**Comment by mikegilchrist** [comment]
Yes, but what's the script you used to cycle through the various genomes. That is, where's the script that defines and uses the  "$INPUT" and "$OUTPUT" variables?

**Comment by acope3** [comment]
See `runROC_parallel.sh`. I use GNU `parallel` to run these my analysis with this bash script. Something like `nohup parallel -j 8 -a <text file with the name of each FASTA file you want to analyze on separate lines> ./runROC_parallel.sh {} &`

The `-j 8` indicates to only allow 8 jobs to run at a time.

**Comment by mikegilchrist** [comment]
`find . -name "runROC_parallel.sh"`  returns no results.  Are you sure it's in the repo?

**Comment by acope3** [comment]
Sorry...`runRoc_parallel.sh`

**Comment by mikegilchrist** [comment]
`find . -iname "*runRoc_parallel*"` also doesn't return anything

**Comment by acope3** [comment]
Double-check that your pull from the repo was successful. It should be there (see image).

![image](https://user-images.githubusercontent.com/21202517/190000927-1ee8e205-0ea9-4e15-9da7-67049632ed13.png)

**Comment by mikegilchrist** [comment]
Ah.  I didn't realize you just added it...

Also, that script must be called by another one in order to define `$1`.  What script calls `runRoc_parallel.sh`?

**Comment by acope3** [comment]
I don't have it as a separate script. Always used GNU `parallel`. 

`nohup parallel -j 8 -a <text file with the name of each FASTA file you want to analyze on separate lines> ./runROC_parallel.sh {} &`

**Comment by mikegilchrist** [comment]
Ahhh... and where might the file used in this study be?

**Comment by acope3** [comment]
Sorry @mikegilchrist, just saw. See the most recent push. Files are `ctg_leu.txt` and `ctg_ser.txt`. These note species that have CTG code for leucine and serine, respectively.
